twist_mux:
  ros__parameters:
    topics:
      cmd_vel_cmd:  
        topic: cmd_vel_ctrl 
        timeout: 0.5
        priority: 20
      keyboard: 
        topic: cmd_vel_key
        timeout: 0.5
        priority: 80
      joystick: 
        topic: cmd_joy
        timeout: 0.5
        priority: 100
      break: 
        topic: cmd_vel_break
        timeout: 1.0
        priority: 255  # Prioridad máxima para control de frenado